export const filters = [
  { name: 'original', class: '' },
  { name: '1977', class: '_1977' },
  { name: 'Aden', class: 'aden' },
  { name: 'Brannan', class: 'brannan' },
  { name: 'Brooklyn', class: 'brooklyn' },
  { name: 'Clarendon', class: 'clarendon' },
  { name: 'Earlybird', class: 'earlybird' },
  { name: 'Gingham', class: 'gingham' },
  { name: 'Hudson', class: 'hudson' },
  { name: 'Inkwell', class: 'inkwell' },
  { name: 'Kelvin', class: 'kelvin' },
  { name: 'Lark', class: 'lark' },
  { name: 'Lo-Fi', class: 'lofi' },
  { name: 'Maven', class: 'maven' },
  { name: 'Mayfair', class: 'mayfair' },
  { name: 'Moon', class: 'moon' },
  { name: 'Nashville', class: 'nashville' },
  { name: 'Perpetua', class: 'perpetua' },
  { name: 'Reyes', class: 'reyes' },
  { name: 'Rise', class: 'rise' },
  { name: 'Slumber', class: 'slumber' },
  { name: 'Stinson', class: 'stinson' },
  { name: 'Toaster', class: 'toaster' },
  { name: 'Valencia', class: 'valencia' },
  { name: 'Walden', class: 'walden' },
  { name: 'Willow', class: 'willow' },
  { name: 'X-pro II', class: 'xpro2' }
]
