export const ActionType = {
  BGCOLOR: 0,
  BGCOLORHEADER: 1,
  BGCOLORSUBTITLE: 2,
  SIZEHEADER: 3,
  SIZESUBTITLTE: 4,
  ALIGNHEADER: 5,
  ALIGNSUBTITLE: 6,
  STYLEHEADERBOLD: 7,
  STYLEHEADERITALIC: 8,
  STYLEHEADERUNDERLINE: 9,
  STYLESUBTITLERBOLD: 10,
  STYLESUBTITLETALIC: 11,
  STYLESUBTITLEUNDERLINE: 12
}
